```python
GRANT  CONTROL  ON  TABLE IXCOM.SENTMESSAGEBUFFERLOG  TO USER  "IXCOM"
GRANT  CONTROL  ON  TABLE "IXCOM"."RECEIVEDMESSAGEBUFFERLOG" TO USER "IXCOM"
GRANT ALTER, USAGE ON SEQUENCE "IXCOM"."SEQ_SENT_MESSAGE" TO USER "IXCOM"
GRANT ALTER, USAGE ON SEQUENCE "IXCOM"."SEQ_RECEIVED_MESSAGE" TO USER "IXCOM"
```
